version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finaid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finaid_user -d finaid"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 