# https://taskfile.dev

version: '3'

vars:
  DBML_FILE: "./schema.dbml"

tasks:
  default:
    desc: "Getting Started"
    cmds:
      - task: install

  install:
    desc: "Install dependencies"
    cmds:
      - go mod download
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/air-verse/air@latest

  dev:
    desc: "Start development server"
    cmd: air

  service:up:
    desc: "Start PostgreSQL service"
    cmds:
      - docker-compose up -d postgres

  service:down:
    desc: "Stop PostgreSQL service"
    cmds:
      - docker-compose down

  db:docs:
    desc: "Generate database documentation from schema.dbml"
    cmds:
      - dbdocs build {{.DBML_FILE}}
